---
title: "Data Science"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

Data is:

* facts or numbers,
* collected to be examined and 
* considered and used to help decision making

*A set of values of qualitative or quantitative variables.*

# RStudio

RStudio is the development environment for R. The toolbar is on top.

* File
  * New File
      * Typically, R script or R markdown is used. But slides etc can also be made. 
* Tools
  * can be used for installing new packages and conenct to GitHub.
* Console
  * Runs R code
* Enrivonment
  * Shows variables etc created. Click to see data
* History
  * Shows commands ran in R 
  * To sorce: writes to R code
* Plots
  * use export to save

There are three main repositories for installing packages:

1. [CRAN](https://cran.r-project.org/web/views/)
2. [Bioconductor repository](https://rdocumentation.org/)
3. [GitHub](https://github.com)

## Important commands

* `install.packages("ggplot2")`: installs ggplot2
  * `remove.packages("ggplot2")` removes it again
* `library(ggplot2)`: opens and initialised ggplot2 for use
  * `detach("package:ggplot2", unload=TRUE)` unloads it again
* `update.packages()`: update all packages
  * `install.packages("ggplot2")`: update ggplot2
* `help(package = "ggplot2")`: Gives info on a package
  * `browseVignettes("ggplot2")`: more detailed documentation
* `version`: info on R installation
* `sessionInfo()`: details on current session.

# Data Analysis

There are six main types of data analysis.

1. Descriptive analysis: describe or summarise a set of data, i.e. describe mean, std dev, etc.
2. Exploratoty analysis: examine data and find relationships that weren't previously known, i.e. find correlations
3. Inferential analysis: use a sample to extrapolate characteristics to a larger group
4. Predictive analysis: Use current and historical data to make predictions about future data
5. Causal analysis: analyse whether a change in one variable leads to a change in another
6. Mechanistic analysis: Understand exact changes in variables that lead to exact changes in other variables

# Big data

In practice, data is rarely structured. The amount of data generated has exploded. We need new tools to mine this data. 

- Volume: there is a lot of data  . Lots of data negates small errors.
- Velocity: the data set is constantly updating. So you can do real time analysis!   
- Variety: what source of data is best suited to answer my question? Unconventional data answers unconventional questions!

In unstructured data, hidden correlations can be resolved. 

# RMarkdown

This document is made using RMarkdown. Text markup, such as __bold__ , _italic_,
`cody` or even ~~strikethrough~~ text is possible. Here below is a code chunk that 
creates a vector and multiplies the elements by 2.

```{r}
a <- c(2, 3 ,6 ,8)
a*2
```
